export const handleError = () => alert('Something went wrong');